apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-export-claim
  labels:
    app: firefly-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-upload-claim
  labels:
    app: firefly-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
--- 
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: firefly-local
  namespace: firefly
  labels:
    app: firefly-local
spec:
  selector:
    matchLabels:
      app: firefly-local
  template:
    metadata:
      labels:
        app: firefly-local
    spec:
      containers:
      - image: firefly-local
        name: firefly-local
        env:
        - name: FF_APP_ENV
          value: "local"
        - name: FF_APP_KEY
          value: "S0m3R@nd0mString0f32Ch@rsEx@ct1y"
        - name: FF_DB_HOST
          value: "172.17.0.9" 
        - name: FF_DB_NAME
          value: "firefly_db"
        - name: FF_DB_USER
          value: "firefly_db"
        - name: FF_DB_PASSWORD
          value: "password" 
        volumeMounts:
        - mountPath: "/var/www/firefly-iii/storage/export"
          name: mysql-persistent-export
        - mountPath: "/var/www/firefly-iii/storage/upload"
          name: mysql-persistent-upload 
        imagePullPolicy: IfNotPresent
      volumes:
        - name: mysql-persistent-export
          persistentVolumeClaim:
            claimName: mysql-pv-export-claim
        - name: mysql-persistent-upload
          persistentVolumeClaim:
            claimName: mysql-pv-upload-claim
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-local
spec:
  ports:
    - port: 80
  type: NodePort
  selector:
    app: firefly-local